# Uncomment this line to define a global platform for your project
platform :ios, '12.0' # Vagy a minimum iOS verzió, amit támogatsz

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Ez a sor betölti a Flutter által generált podhelper.rb fájlt
  # A __dir__ a Podfile mappáját jelöli (ios/), ahonnan a 'Flutter/podhelper.rb' relatívan elérhető
  load File.join(__dir__, 'Flutter', 'podhelper.rb')

  flutter_install_all_ios_pods # A flutter_application_path már nem szükséges itt

  target 'RunnerTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
